#!/usr/bin/env ruby
# frozen_string_literal: true

# Unbuffer stderr so [tags] log lines appear immediately even when stderr is
# piped/redirected (block-buffered by default in those cases).
$stderr.sync = true
$stdout.sync = true

$LOAD_PATH.unshift(File.expand_path("../lib", __dir__))
require "exe32_rb"
require "exe32_rb/cli"

exit Exe32Rb::CLI.new(ARGV).run
